version: '2'
services:
    joomla:
      build: .
      links:
          - joomladb
      ports:
          - "8081:80"
      volumes:
          - .:/var/www/html
    joomladb:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
          - .:/var/www/html